# Generated by Django 4.2.16 on 2026-01-27 06:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_add_new_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='shop_order_user_id_f8b1c9_idx',
            old_name='shop_order_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='shop_order_status_63c2c0_idx',
            old_name='shop_order_status_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_categor_2b6bbc_idx',
            old_name='shop_produc_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_created_ddfb00_idx',
            old_name='shop_produc_created_idx',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='shop_produc_product_69a799_idx',
            old_name='shop_produc_product_idx',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
